name: Q3

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Q3_archive_java.txt
        run: |
          echo "Nom et Prénom: AAAB Anas" > Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      - name: Commit and push new file
        run: |
          git config --global user.name "Fletcher-Prog"
          git config --global user.email "aarab.anas04@gmail.com"
          git add Q3_archive_java.txt
          git commit -m "Archive Q3.java as Q3_archive_java.txt"
          git push
